### ISSUE TITLE
Arduino compatibility

### ISSUE THREAD

**Issue by eried** [nrwiersma/ESP8266Scheduler#15]
Can this run on AVR? I always use your library for my ESP projects, but I am trying to make a small project with a screen that runs on both platforms. Any ideas?

**Comment by nrwiersma** [comment]
I mean you could try, but i highly doubt it. It is based around the ESP8266 [cont.h](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/cont.h) to do the stack context switching. This is in turn based around the ESP8266 chip design i believe. Not even sure it would work on an ESP32.

**Comment by eried** [comment]
ah, it requires extra work. I need to think on a solution maybe with something like: https://github.com/mikaelpatel/Arduino-Scheduler mixed with your wrapper. Or maybe some thin layer with #ifdef for both architectures :/
