### ISSUE TITLE
Removal of main Task to save ram

### ISSUE THREAD

**Issue by dbuezas** [nrwiersma/ESP8266Scheduler#18]
If I read the code correctly, the main Task is just a placeholder to hold prev and next, which is very elegant but it unnecessarily takes 4k of RAM.

declaring it as a pointer and using the first started task in its place saves almost 5k.

```cpp
Task *SchedulerClass::main = NULL;
Task *SchedulerClass::current = NULL;
SchedulerClass::SchedulerClass() {}

void SchedulerClass::start(Task *task) {
  if (!main) {
    main = task;
    current = main;
    main->next = main;
    main->prev = main;
  }
  task->next = main;
  task->prev = main->prev;

  main->prev->next = task;
  main->prev = task;
}
```

My sketch seems to be working fine with this and allows me an extra concurrent task.
From experiments, it seems like 24k of free heap are necessary to establish an SSL connection, so this makes a big difference (3 concurrent tasks can run ok)

**Comment by nrwiersma** [comment]
Hey, this seems like a great idea. Why dont you make a PR to this effect.
