### ISSUE TITLE
Allow for an extra "free" task

### ISSUE THREAD

**Issue by dbuezas** [nrwiersma/ESP8266Scheduler#19]
Given that Tasks are memory hungry, would you consider calling the global loop function after all tasks went through a cycle?
Of course that a delay in the global loop would block all tasks, but this "thread" can still be useful for things like `ArduinoOTA.handle();` or checking the serial input.

**Comment by dbuezas** [comment]
I made this change and it works well:
```cpp
void SchedulerClass::begin() {
  while (1) {
    if (current->shouldRun()) cont_run(&current->context, task_tramponline);
    ::loop(); // <------- added this line
    yield();

    current = current->next;
  }
}
```

**Comment by nrwiersma** [comment]
Hi,

This is a nice idea, but not always wanted or expected. Instead I would suggest that the user can provide a callback that should be run inbetween tasks if it exists. This way the current behaviour is default, but you can still achieve what you want.

PRs to this effect would be welcome.

**Comment by dbuezas** [comment]
All right, I'll make the PR in the coming days :)
You ok with the PR moving from a circular double linked list to a non-circular linked list with pointers to first and last? the extra callback will be called after last and before first.

**Comment by nrwiersma** [comment]
Yes, that is fine. The `prev` is only used to link tasks.

**Comment by dbuezas** [comment]
I've been fiddling a bit with the concept and although it works and it is sort of intuitive, I find myself implementing a similar concept in the "main" task. I have a couple of "fast tasks" which don't have delays in the middle of the code (so no need for an extra context), but that also need to run every once a while.

---
### Something like this
#### Fast (low ram) Tasks
* update the screen every second
* call ArduinoOTA.handle(); on every opportunity
* read some sensors every 4 seconds
* etc.
#### Real Tasks (4k extra ram per task)
* Send a GET request every minute, but release the cpu while waiting for a response
* If disconnected from the wifi, start the connection and then reset some variables, but release the cpu while waiting.
---

Obviously the "fast tasks" can be implemented in the main context, but the code looks much better if I can add them to the scheduler *as if they were regular tasks*.

#### Getting to the point
I made a **SuperTask**, from which both **Tasks** and **FastTasks** inherit *and both can be added via Scheduler.start*.
* **FastTasks** don't have instance methods for delay and yield but Instead they have a "schedule(uint32_t ms)" method which just signals "don't call this loop again for a while".
* **Tasks** are your original concurrent tasks, which are quite RAM intensive

* It works well
* memory efficient (so I can do my SSL requests)
* it doesn't add much more code or complexity (imho)
* it can obviously do the same and more than the original idea.
* there are no breaking changes

---

### What do you think about this? 
---> I'd like to make a PR with it instead of yesterday's idea. <---

Here's some dummy example code:
```cpp

class WifiTask : public Task {
  void setup() {}
  void loop() {
    if (WiFi.status() != WL_CONNECTED) {
      delay(100);
    }
    doTheThingAfterConnecting();
  }
} wifi_task;
class RequestsTask : public Task {
  void setup() {}
  void loop() {
    if (WiFi.status() == WL_CONNECTED) {
      updateStateToIndicateProgressInDisplay();
      sendRequest();
      while (!done){ yield(); }
      updateStateToShowInDisplayThatRequestIsDone();
    }
  }
} wifi_task;

class OtaTask : public FastTask {
  void setup() {}
  void loop() {
    ArduinoOTA.handle();
  }
} wifi_task;
class DisplayTask : public FastTask {
  void setup() {}
  void loop() {
    updateScreen();
    schedule(1000); // <-- means wait a second before running again
  }
} display_task;
class SensorsTask : public FastTask {
  void setup() {}
  void loop() {
    readSensors();
    schedule(4000); // <-- means wait 4 seconds before running again
  }
} sensors_task;

void setup(){
  // Normal tasks:
  Scheduler.start(&wifi_task);
  Scheduler.start(&requests_task);
  // Fast tasks that take no extra ram
  Scheduler.start(&wifi_ota_task);
  Scheduler.start(&sensors_task);
  Scheduler.start(&display_task);

  Scheduler.begin();
}

void loop(){}
```

**Comment by nrwiersma** [comment]
It seems to be a good idea, I think a PR to this effect would be very interesting indeed.

**Comment by dbuezas** [comment]
I'll abandon this PR. Without test code for the run groups I may break them. 

I don't have a personal use case this original synchronisation concept and I prefer to synch tasks in "user code" with standard methods. So I'll keep my version with "lean tasks" in my repo for my own use :)

Thanks for considering it!

**Comment by dbuezas** [comment]
if any future reader needs this, it is available here: https://github.com/dbuezas/ESP8266Scheduler
