### ISSUE TITLE
Add Scheduler.Stop();

### ISSUE THREAD

**Issue by M0ISTHaxx** [nrwiersma/ESP8266Scheduler#25]
something like Scheduler.Stop(&task);

**Comment by nrwiersma** [comment]
You are going to need to complete the idea here. Who do you expect to call this? And to what end. 

Once the Scheduler is started, only tasks and the scheduler run, so who should call this? Some some task choose to stop another task? Is that wise? If a task should stop itself, this can already achieved in an encapsulated way.
