### ISSUE TITLE
Documentation has a "typo"

### ISSUE THREAD

**Issue by ricardomogio2** [nrwiersma/ESP8266Scheduler#26]
Hey, it's not an issue;
Is something I've found, that maybe you made a mistake, because to write a digital output, we should use digitalWrite:

Current doc:
`class BlinkTask : public Task {
protected:
    void setup() {
        state = HIGH;

        pinMode(2, OUTPUT);
        pinMode(2, state);
    }

    void loop() {
        state = state == HIGH ? LOW : HIGH;
        **pinMode(2, state);**

        delay(1000);
    }

private:
    uint8_t state;
} blink_task;`,

This bolded line should be replaced with
`digitalWrite(2, state)`

**Comment by nrwiersma** [comment]
Hey, thanks for pointing this out. I am fixing it.
